/* Hadoop Hive DDL Generated by BIM 1.0 */

CREATE TABLE IF NOT EXISTS ed_work.Genre
(
  genre_id INT,
  parent INT,
  title STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ‘,’
LINES TERMINATED BY ‘\n’
;

load data inpath '/home/hduser/Desktop/Filtered_Genres.csv' into table ed_work.Genre;



CREATE TABLE ed_work.Track
(
  track_id INT,
  bitrate INT,
  genre_top, STRING,
  duration INT,
  title VARCHAR,
  mfcc: DECIMAL,
  [restantes features, são mais de 300 colunas]
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ‘,’
LINES TERMINATED BY ‘\n’;

load data inpath '/home/hduser/Desktop/Filtered_Tracks.csv' into table ed_work.Track;

